name: CI/CD with Codecov

on:
  push:
    branches:
      - main # Înlocuiește cu numele branch-ului principal al tău

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        run: |
          echo "JAVA_HOME=C:\\Program Files\\Java\\jdk-17" >> $GITHUB_ENV
          echo "PATH=\$JAVA_HOME\\bin:\$PATH" >> $GITHUB_ENV
          java -version

      - name: Make ./gradlew executable
        run: chmod +x ./gradlew

      - name: Build and run tests
        run: |
          # Înlocuiește aceste comenzi cu comenzile tale reale de build și test
          ./gradlew build
          ./gradlew test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
